# Dataset for training the Expense Categorizer
EXPENSE_TRAINING_DATA = [
    # Food
    ("mcdonalds burger", "food"),
    ("starbucks coffee latte", "food"),
    ("burger king meal", "food"),
    ("grocery store supermarket", "food"),
    ("walmart grocery delivery", "food"),
    ("pizza hut delivery pizza", "food"),
    ("sushi restaurant dining", "food"),
    ("cafe breakfast coffee", "food"),
    ("bakery bread cake", "food"),
    ("dinner at local diner", "food"),
    ("uber eats food delivery", "food"),
    ("doordash lunch delivery", "food"),
    ("subway sandwich cookies", "food"),
    ("kfc fried chicken bucket", "food"),
    ("taco bell dinner", "food"),
    ("grocery shopping organic veggies", "food"),
    ("weekly groceries at safeway", "food"),
    ("snacks chips sodas", "food"),
    ("whole foods market", "food"),
    ("ramen shop noodles", "food"),

    # Transport
    ("uber ride to office", "transport"),
    ("lyft taxi to airport", "transport"),
    ("gas station fuel fillup", "transport"),
    ("petrol station gas payment", "transport"),
    ("shell gas station", "transport"),
    ("chevron fuel", "transport"),
    ("subway transit ticket", "transport"),
    ("train fare commuter pass", "transport"),
    ("bus ride ticket", "transport"),
    ("parking garage ticket", "transport"),
    ("highway toll payment", "transport"),
    ("flight ticket booking flight", "transport"),
    ("airline booking trip", "transport"),
    ("cab ride home", "transport"),
    ("taxi fare cash payment", "transport"),
    ("car service maintenance", "transport"),
    ("train ticket monthly card", "transport"),
    ("metro card recharge", "transport"),
    ("gasoline fillup car", "transport"),
    ("road trip tolls", "transport"),

    # Utilities
    ("electric bill power grid", "utilities"),
    ("electric company monthly payment", "utilities"),
    ("water bill sewage charge", "utilities"),
    ("gas heating company utility", "utilities"),
    ("internet bill broadband wifi", "utilities"),
    ("comcast xfinity internet service", "utilities"),
    ("broadband high speed net", "utilities"),
    ("garbage collection fee", "utilities"),
    ("trash disposal bill", "utilities"),
    ("electricity billing service", "utilities"),
    ("energy bill utilities", "utilities"),
    ("power bill", "utilities"),
    ("water and waste bill", "utilities"),
    ("gas bill winter heating", "utilities"),
    ("heating oil utilities", "utilities"),

    # Subscriptions
    ("netflix monthly video subscription", "subscriptions"),
    ("spotify family music plan", "subscriptions"),
    ("hulu streaming service", "subscriptions"),
    ("amazon prime yearly subscription", "subscriptions"),
    ("disney plus premium stream", "subscriptions"),
    ("youtube premium ad-free plan", "subscriptions"),
    ("gym membership fit fitness club", "subscriptions"),
    ("saas monthly cloud subscription", "subscriptions"),
    ("github copilot subscription developer", "subscriptions"),
    ("software license renewal", "subscriptions"),
    ("hbo max movie subscription", "subscriptions"),
    ("apple music subscription", "subscriptions"),
    ("adobe creative cloud subscription", "subscriptions"),
    ("newspaper digital subscription wsj", "subscriptions"),
    ("magazine subscription monthly", "subscriptions"),

    # Medical
    ("pharmacy medicine prescription", "medical"),
    ("cvs pharmacy health checkout", "medical"),
    ("walgreens drugs pills", "medical"),
    ("doctor clinic checkup visit", "medical"),
    ("dentist teeth cleaning cavity", "medical"),
    ("hospital emergency visit clinic", "medical"),
    ("health insurance premium monthly", "medical"),
    ("medicine bill prescription refill", "medical"),
    ("medical clinic appointment fee", "medical"),
    ("eye care glasses contact lenses", "medical"),
    ("dental checkup appointment", "medical"),
    ("pediatrician clinic health", "medical"),
    ("physiotherapy therapy clinic", "medical"),
    ("antibiotics pills pharmacy", "medical"),

    # Education
    ("tuition fees college semester", "education"),
    ("coursera certificate online course", "education"),
    ("udemy python programming course", "education"),
    ("textbooks college school bookstore", "education"),
    ("school supplies stationaries notebooks", "education"),
    ("college registration application", "education"),
    ("online masterclass subscription learning", "education"),
    ("seminar lecture ticket training", "education"),
    ("coding bootcamp payment fees", "education"),
    ("academic tutor science lessons", "education"),

    # Shopping
    ("amazon online shopping electronics", "shopping"),
    ("clothing store jeans jacket", "shopping"),
    ("target department store items", "shopping"),
    ("nike sneakers sport shoes", "shopping"),
    ("running shoes department shopping", "shopping"),
    ("ikea home furniture table chairs", "shopping"),
    ("electronics purchase computer hardware", "shopping"),
    ("best buy TV laptop purchase", "shopping"),
    ("shopping mall dress checkout", "shopping"),
    ("h&m retail apparel store", "shopping"),
    ("zara online fashion shopping", "shopping"),
    ("department store home goods walmart", "shopping"),
    ("shoes and clothes department", "shopping"),
    ("birthday gift shopping toy store", "shopping"),
    ("paid apartment rent for this month", "utilities"),
    ("monthly water bill payment", "utilities"),
    ("sprint phone bill payment", "utilities"),
    ("netflix subscription renewal fee", "subscriptions"),
    ("spotify family plan payment", "subscriptions"),
    ("doctor checkup cash payment", "medical"),
    ("lab test clinic bill", "medical"),
    ("college tuition semester fees", "education"),
    ("online course subscription payment", "education"),
    ("new laptop electronics purchase", "shopping"),
    ("birthday present from mall", "shopping"),
]

# Dataset for training the Chat Intent Classifier
INTENT_TRAINING_DATA = [
    # savings
    ("how can I save more money?", "savings"),
    ("what is my savings rate?", "savings"),
    ("how should I build an emergency fund?", "savings"),
    ("tips for saving for a house goal", "savings"),
    ("tell me about savings plans", "savings"),
    ("i want to invest and save money", "savings"),
    ("how to save 30 percent of my income?", "savings"),
    ("what is the best savings strategy?", "savings"),
    ("tell me how to grow my emergency fund fast", "savings"),
    ("help me save for retirement", "savings"),

    # reduction
    ("how to cut down my expenses?", "reduction"),
    ("where am I spending too much?", "reduction"),
    ("how can I reduce my category costs?", "reduction"),
    ("tell me how to lower my grocery spending", "reduction"),
    ("optimize my spending habits", "reduction"),
    ("where should I cut my budget?", "reduction"),
    ("how to reduce subscription bills?", "reduction"),
    ("tips to trim my daily spend", "reduction"),
    ("help me spend less in food", "reduction"),
    ("identify unnecessary expenses to lower", "reduction"),

    # weekly
    ("give me a weekly spending budget", "weekly"),
    ("what is my weekly cap limit?", "weekly"),
    ("how much can I spend per week?", "weekly"),
    ("break down my spending week by week", "weekly"),
    ("show me a weekly view plan", "weekly"),
    ("what is a healthy weekly allowance?", "weekly"),
    ("weekly budget breakdown", "weekly"),
    ("can you split my wants budget into weeks?", "weekly"),
    ("tell me my weekly safe to spend", "weekly"),

    # budget_planning
    ("help me create a spending plan", "budget_planning"),
    ("how should I allocate my 60000 income?", "budget_planning"),
    ("explain the 50/30/20 budget rule allocation", "budget_planning"),
    ("how to distribute my balance?", "budget_planning"),
    ("give me a simple budget plan for my salary", "budget_planning"),
    ("how should I divide my monthly pay?", "budget_planning"),
    ("create a budget allocation mapping", "budget_planning"),
    ("how to plan my budget this month?", "budget_planning"),
    ("help me map my income", "budget_planning"),

    # general
    ("how does my budget look right now?", "general"),
    ("tell me about my financial health", "general"),
    ("summarize my income and expense balance", "general"),
    ("show my top categories summary", "general"),
    ("what is my current balance?", "general"),
    ("give me general financial advice", "general"),
    ("how am I doing this month?", "general"),
    ("can you review my budget profile?", "general"),
    ("status of my expenses", "general"),

    # forecast / prediction
    ("what will my expenses look like next month?", "forecast"),
    ("predict my upcoming monthly expenses", "forecast"),
    ("forecast my budget for next month", "forecast"),
    ("will my spending increase next month?", "forecast"),
    ("how much should I expect to spend next month?", "forecast"),
    ("project next month's expenses based on current trends", "forecast"),
    ("give me a forecast for my monthly spending", "forecast"),
    ("estimate my spending for the next month", "forecast"),
    ("what will my budget look like next month?", "forecast"),
    ("how much should I budget for the next month?", "forecast"),
    ("can you predict my next month spending?", "forecast"),
    ("show me a forecast for my future expenses", "forecast"),
    ("tell me how much I might spend next month", "forecast"),
    ("what is the expected cost next month?", "forecast"),
    ("do I need to increase my budget for next month?", "forecast"),
    ("should I expect higher expenses in the next month?", "forecast"),
    ("project my monthly cost for the coming month", "forecast"),
    ("how will my spending trend next month?", "forecast"),
    ("forecast my next month's bills and expenses", "forecast"),
    ("give me a prediction for my upcoming monthly expenses", "forecast"),
    ("what should I plan for next month’s spending?", "forecast"),
    ("will my expenses go up or down next month?", "forecast"),
    ("estimate next month’s expense total", "forecast"),
    ("help me forecast the next month based on current data", "forecast"),

    # anomaly / unusual transactions
    ("is any recent transaction unusual?", "anomaly"),
    ("detect anomalies in my spending", "anomaly"),
    ("flag suspicious or outlier expenses", "anomaly"),
    ("which of my transactions look abnormal?", "anomaly"),
    ("alert me to any outlier spending this month", "anomaly"),

    # investment / retirement
    ("should I invest or save this month?", "investment"),
    ("how to start investing for retirement?", "investment"),
    ("what is a safe investment plan for a beginner?", "investment"),
    ("how to allocate between stocks and bonds?", "investment"),
    ("retirement planning steps for a 30-year-old", "investment"),
    ("what is the best way to build retirement savings?", "investment"),
]
